config/routes.rb
Rails.application.routes.draw do

  get '/' => 'site#home'
  get '/contact' => 'site#contact'

  resources :projects, only: [:index, :show] do
    resources :entries, only: [:index, :new, :create, :edit, :update, :destroy]
  end

end
  

  #   end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :project

  validates :hours, :minutes, numericality: { only_integer: true }
  validates :date, :hours, :minutes, presence: true
  validates :project_id, presence: true

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :entries

  validates :name, uniqueness: true
  validates :name, presence: true
  validates :name, length: { maximum: 30 }
  validates :name, format: { with: /\A[A-Za-z0-9ñÑ]+[A-Za-z0-9ñÑ\ ]+\z/ }

  def self.iron_find(params)
    where(params).first
  end

  def self.clean_old
    where('create_at < ?', Time.now - 1.week).destroy_all
  end

  def self.last_created_projects(max) 
    order('created_at DESC').limit(max)
  end

  def self.first_updated_projects(max)
    order('updated_at ASC').limit(max)
  end

  def total_hours_in_month(month, year)
    from = Date.new(year,month,1)
    to = from.end_of_month

    month_entries = entries.where(date: from..to)
    
    
    total_minutes = month_entries.reduce(0) do |sum, entry|
      sum + entry.minutes + entry.hours * 60
    end

    total_hours = total_minutes / 60.0
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def render_404(params)
    Rails.logger.warn("Tried to access #{params} which did not exist.")
    render "layouts/404"
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def index
    @date = Date.today
    @project = Project.find_by(id: params[:project_id])
    @entries = @project.entries.where(date: @date.beginning_of_month..@date.end_of_month)
# send to application helper -> @total_hours = @project.total_hours_in_month(date.month, date.year)
  end

  def new
    @project = Project.find(params[:project_id])
    @entry = @project.entries.new #new entry with project_id
  end

  def create
    @project = Project.find(params[:project_id])
    @entry = @project.entries.new(entry_params)

    if @entry.save
      flash[:notice] = 'Entry created successfully'
      redirect_to action: 'index', controller: 'entries', project_id: @project.id
    else
      flash[:alert] = 'Sorry, something went wrong:'
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:project_id])
    @entry = @project.entries.find(params[:id])
  end

  def update
    @project = Project.find(params[:project_id])
    @entry = @project.entries.find(params[:id])

    if @entry.update_attributes(entry_params)
      redirect_to action: 'index', controller: 'entries', project_id: @project.id
    else      
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @entry = @project.entries.find(params[:id])

    @entry.destroy
    redirect_to action: 'index', controller: 'entries', project_id: @project.id
  end

  private

  def entry_params
    params.require(:entry).permit(:hours, :minutes, :date)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.last_created_projects(10)
      if @projects.empty?
        render 'no_projects_found' #render template: 'ruta alternativa desde views'
      end
  end

  def show
    @project = Project.find_by(id: params[:id]) ||
      render_404(params) # defined in application_controller
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    
  end

  def contact

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_message
    display_message(:alert) || display_message(:notice)
  end

  private

  def display_message(type)
    if flash[type]
      content_tag :div, class: "message #{type}" do
        content_tag :p do
          flash[type]
        end
      end
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def current_month_hours_for_project(project, date)
    project.total_hours_in_month(date.month, date.year)
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/entries/_form.html.erb
<%= flash_message %>

<% if @entry.errors.any? %>
  <ul>
    <% @entry.errors.full_messages.each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [@project, @entry] do |f| %>
  <%= f.label :hours %>
  <%= f.text_field :hours %>
  <br>
  <%= f.label :minutes %>
  <%= f.text_field :minutes %>
  <br>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br>

  <%= f.submit 'Save' %>  <%= link_to("Cancel", project_entries_path(@project)) %>
<% end %>

app/views/entries/edit.html.erb
<h2>Editing the entry in <%= @project.name %> project</h2>

<%= render 'form' %>

app/views/entries/index.html.erb
<h1><%= @project.name %></h1>

<h2><%= @project.description %></h2>

<%= flash_message %>

<br>

<%= link_to("< Go back to projects", projects_path) %>
<%= link_to("+ Create new entry", new_project_entry_path(@project)) %>

<h3>The total time worked this month: <%= current_month_hours_for_project(@project, @date) %> hours</h3>

<ul>
  <% @entries.each do |entry| %>
    <li>
      <%= entry.hours %>h <%= entry.minutes %> m · <%= entry.date.year %>-<%= entry.date.month %>-<%= entry.date.day %>
      <%= link_to("Edit", edit_project_entry_path(@project, entry)) %>
      <%= link_to("Delete", project_entry_path(@project, entry), method: :delete, data: { confirm: 'Are you sure?' }) %>
    </li>
  <% end %>
</ul>

app/views/entries/new.html.erb
<h2>Creating a new entry in <%= @project.name %> project</h2>

<%= render 'form' %>

app/views/layouts/404.html.erb
<h1>Error 404</h1>

<p>by timetracking</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <header>
      Time tracking tool
    </header>

    <%= yield %>

    <footer>
      Ironhack - Rails introduction
    </footer>
  </div>
</body>
</html>

app/views/layouts/no_projects.html.erb
<h1>Time Tracking</h1>

<p>There's no projects</p>

<p>layout no_projects</p>

app/views/projects/index.html.erb
<h1>Your projects</h1>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= link_to(project.name, project_entries_path(project)) %>
      <% if project.description.present? %>
       - <%= project.description %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/projects/no_projects_found.html.erb
<h1>There's no projects</h1>

<p>wiew in projects no_projects_found</p>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<p><%= @project.description %></p>

app/views/site/contact.html.erb
<h1>Contact</h1>

<a href="mailto:contact@example.com">contact@example.com</a>

app/views/site/home.html.erb
<h1>Welcome to this timetracking tool</h1>

<p>Ironhack powered</p>